# Generated by Django 5.1.6 on 2025-02-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caffe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('items', models.JSONField()),
                ('total_price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
