# Generated by Django 5.1.6 on 2025-02-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caffe',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
